#!/bin/bash




geth --rinkeby --fast  --rpc --rpcapi db,eth,net,web3,personal --cache=512 --rpcport 8545 --rpcaddr 127.0.0.1 --rpccorsdomain "*" --datadir  /Volumes/External/Ethereum_project/Blockchain_Networks/Rinkeby/
